### ISSUE TITLE
Server-side "caching" (storage)

### ISSUE THREAD

**Issue by littledivy** [johnletey/cacheweave#5]
https://www.npmjs.com/package/node-localstorage

**Comment by johnletey** [comment]
@littledivy Keep your eye on [`localPorridge`](https://github.com/johnletey/localPorridge) 😉

**Comment by johnletey** [comment]
Implemented in https://github.com/johnletey/cacheweave/commit/de3ba6646ff73015cb8c784af933b1ad4cd36b36.

The `localPorridge` library has a ways to go, but it's working 🙌🏻

---

<img width="1136" alt="Screenshot_2020-10-17_at_19 39 54" src="https://user-images.githubusercontent.com/62398724/96351170-929dc100-10b1-11eb-9ca6-ef4acd293ab4.png">

> Example of this in action 😁
